## CEBD 1260 Introduction to big data and machine learning

## Week2 - Assignments ( 1 to 5 ) 

Data set used: Home credit risk 

Student: Katayoun B. 
Email: katayounb@gmail.com


### import important libs

In [1]:
import numpy as np   # import numpy
import pandas as pd  # import pandas
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

### Before starting the assignments, I tried to read my data, then I will split input and target variables.

#### Assignment 1:
please read and split input and output for your own project data and understanding in details

In [2]:
df = pd.read_csv('data/application_train.csv')
#df

In [3]:
#get some info from data frame
print(df.shape)

(307511, 122)


In [4]:
# check the data 
df.head()
# df.head(3)
# df.tail()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

In [5]:
df.info() # this give you more infor about data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB


In [6]:
des = df.describe() # describe the statistical property of the data
des

SK_ID_CURR         TARGET   CNT_CHILDREN  AMT_INCOME_TOTAL  \
count  307511.000000  307511.000000  307511.000000      3.075110e+05   
mean   278180.518577       0.080729       0.417052      1.687979e+05   
std    102790.175348       0.272419       0.722121      2.371231e+05   
min    100002.000000       0.000000       0.000000      2.565000e+04   
25%    189145.500000       0.000000       0.000000      1.125000e+05   
50%    278202.000000       0.000000       0.000000      1.471500e+05   
75%    367142.500000       0.000000       1.000000      2.025000e+05   
max    456255.000000       1.000000      19.000000      1.170000e+08   

         AMT_CREDIT    AMT_ANNUITY  AMT_GOODS_PRICE  \
count  3.075110e+05  307499.000000     3.072330e+05   
mean   5.990260e+05   27108.573909     5.383962e+05   
std    4.024908e+05   14493.737315     3.694465e+05   
min    4.500000e+04    1615.500000     4.050000e+04   
25%    2.700000e+05   16524.000000     2.385000e+05   
50%    5.135310e+05   24903.000000     4.500000e+05   
75%    8.086500e+05   34596.000000     6.795000e+05   
max    4.050000e+06  258025.500000     4.050000e+06   

       REGION_POPULATION_RELATIVE     DAYS_BIRTH  DAYS_EMPLOYED  ...  \
count               307511.000000  307511.000000  307511.000000  ...   
mean                     0.020868  -16036.995067   63815.045904  ...   
std                      0.013831    4363.988632  141275.766519  ...   
min                      0.000290  -25229.000000  -17912.000000  ...   
25%                      0.010006  -19682.000000   -2760.000000  ...   
50%                      0.018850  -15750.000000   -1213.000000  ...   
75%                      0.028663  -12413.000000    -289.000000  ...   
max                      0.072508   -7489.000000  365243.000000  ...   

       FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
count     307511.000000     307511.000000     307511.000000     307511.000000   
mean           0.008130          0.000595          0.000507          0.000335   
std            0.089798          0.024387          0.022518          0.018299   
min            0.000000          0.000000          0.000000          0.000000   
25%            0.000000          0.000000          0.000000          0.000000   
50%            0.000000          0.000000          0.000000          0.000000   
75%            0.000000          0.000000          0.000000          0.000000   
max            1.000000          1.000000          1.000000          1.000000   

       AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
count               265992.000000              265992.000000   
mean                     0.006402                   0.007000   
std                      0.083849                   0.110757   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      4.000000                   9.000000   

       AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
count               265992.000000              265992.000000   
mean                     0.034362                   0.267395   
std                      0.204685                   0.916002   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      8.000000                  27.000000   

       AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
count              265992.000000               265992.000000  
mean                    0.265474                    1.899974  
std                     0.794056                    1.869295  
min                     0.000000                    0.000000  
25%              

In [7]:
y = df['TARGET'].values# define target 
y

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [8]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [9]:
# get a full list of features we will use for input
features = [f for f in df.columns.values if f not in ['TARGET']] 
print(features)

['SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG

In [10]:
df.drop(['TARGET'],axis=1,inplace=True)

In [11]:
df.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0      100002         Cash loans           M            N               Y   
1      100003         Cash loans           F            N               N   
2      100004    Revolving loans           M            Y               Y   
3      100006         Cash loans           F            N               Y   
4      100007         Cash loans           M            N               Y   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          202500.0    406597.5      24700.5         351000.0   
1             0          270000.0   1293502.5      35698.5        1129500.0   
2             0           67500.0    135000.0       6750.0         135000.0   
3             0          135000.0    312682.5      29686.5         297000.0   
4             0          121500.0    513000.0      21865.5         513000.0   

   ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                0                0                0                0   
1  ...                0                0                0                0   
2  ...                0                0                0                0   
3  ...                0                0                0                0   
4  ...                0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        NaN                        NaN   
4                        0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 121 columns]

In [12]:
X = df[features] # get X
#X

In [13]:
print(X.shape,len(y))

(307511, 121) 307511


In [14]:
X.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0      100002         Cash loans           M            N               Y   
1      100003         Cash loans           F            N               N   
2      100004    Revolving loans           M            Y               Y   
3      100006         Cash loans           F            N               Y   
4      100007         Cash loans           M            N               Y   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          202500.0    406597.5      24700.5         351000.0   
1             0          270000.0   1293502.5      35698.5        1129500.0   
2             0           67500.0    135000.0       6750.0         135000.0   
3             0          135000.0    312682.5      29686.5         297000.0   
4             0          121500.0    513000.0      21865.5         513000.0   

   ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                0                0                0                0   
1  ...                0                0                0                0   
2  ...                0                0                0                0   
3  ...                0                0                0                0   
4  ...                0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        NaN                        NaN   
4                        0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 121 columns]

#### Assignment 2:
please identify categorical features for your own data, you need to use some coding and your own understanding from the data

In [15]:
# print data type for each feature
for f in features:
    print(" {}: {}".format(f,df[f].dtype))

 SK_ID_CURR: int64
 NAME_CONTRACT_TYPE: object
 CODE_GENDER: object
 FLAG_OWN_CAR: object
 FLAG_OWN_REALTY: object
 CNT_CHILDREN: int64
 AMT_INCOME_TOTAL: float64
 AMT_CREDIT: float64
 AMT_ANNUITY: float64
 AMT_GOODS_PRICE: float64
 NAME_TYPE_SUITE: object
 NAME_INCOME_TYPE: object
 NAME_EDUCATION_TYPE: object
 NAME_FAMILY_STATUS: object
 NAME_HOUSING_TYPE: object
 REGION_POPULATION_RELATIVE: float64
 DAYS_BIRTH: int64
 DAYS_EMPLOYED: int64
 DAYS_REGISTRATION: float64
 DAYS_ID_PUBLISH: int64
 OWN_CAR_AGE: float64
 FLAG_MOBIL: int64
 FLAG_EMP_PHONE: int64
 FLAG_WORK_PHONE: int64
 FLAG_CONT_MOBILE: int64
 FLAG_PHONE: int64
 FLAG_EMAIL: int64
 OCCUPATION_TYPE: object
 CNT_FAM_MEMBERS: float64
 REGION_RATING_CLIENT: int64
 REGION_RATING_CLIENT_W_CITY: int64
 WEEKDAY_APPR_PROCESS_START: object
 HOUR_APPR_PROCESS_START: int64
 REG_REGION_NOT_LIVE_REGION: int64
 REG_REGION_NOT_WORK_REGION: int64
 LIVE_REGION_NOT_WORK_REGION: int64
 REG_CITY_NOT_LIVE_CITY: int64
 REG_CITY_NOT_WORK_CITY: int64


In [16]:
#pickup all features that are categorical
cat_features = []
for f in features:
    if str(df[f].dtype) == 'object':
        cat_features.append(f)
print(cat_features)
#len(cat_features)  
# as you see above there 16 categorical features in my dataset 

['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']


In [17]:
# This is just another extra step for myself to see 
# sometimes we need to really see if one feature is categorical based on our domain knowledge or common sense
cat_features = []
for f in features:
    if str(df[f].dtype) in ['object','int64','casual']:
        cat_features.append(f)
print(cat_features)
len(cat_features) 

['SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLA

56

#### Assignment 3: 

please split your own project data train,valid,test by 20%,25% from the total data set

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
# split 20% data as test data
train_X,test_X,train_y,test_y = train_test_split(X,y,shuffle=True,random_state=2019,test_size=0.2)
print(train_X.shape,test_X.shape,len(train_y),len(test_y))

(246008, 121) (61503, 121) 246008 61503


In [20]:
# split 25% data as test data  - just to the difference 
#train_X,test_X,train_y,test_y = train_test_split(X,y,shuffle=True,random_state=2019,test_size=0.25)
#print(train_X.shape,test_X.shape,len(train_y),len(test_y))
# out put was (230633, 121) (76878, 121) 230633 76878

In [21]:
# split another 20% data as valid data, NOTE that you cannot touch test data again
train_X,valid_X,train_y,valid_y = train_test_split(train_X,train_y,shuffle=True,random_state=668,test_size=0.2)
print(train_X.shape,valid_X.shape,len(train_y),len(valid_y))

(196806, 121) (49202, 121) 196806 49202


In [22]:
len(X),len(train_X),len(valid_X),len(test_X)

(307511, 196806, 49202, 61503)

In [23]:
len(X), len(train_X)+len(valid_X)+len(test_X)

(307511, 307511)

#### Assignment 4: 
practice cross validation split by your own data

In [24]:
from sklearn.model_selection import KFold

In [25]:
kf = KFold(n_splits=5,random_state=2019,shuffle=True)
for train_idx,valid_idx in kf.split(X,y):
    print(train_idx,valid_idx)

[     0      1      2 ... 307508 307509 307510] [     7     18     20 ... 307502 307503 307507]
[     2      3      4 ... 307507 307509 307510] [     0      1      8 ... 307489 307499 307508]
[     0      1      2 ... 307507 307508 307509] [     3      4      6 ... 307494 307506 307510]
[     0      1      3 ... 307508 307509 307510] [     2     10     11 ... 307496 307504 307505]
[     0      1      2 ... 307507 307508 307510] [     5     12     13 ... 307500 307501 307509]


In [26]:
for train_idx,valid_idx in kf.split(X,y):
    train_X = X.loc[train_idx]
    train_y = y[train_idx]
    
    valid_X = X.loc[valid_idx]
    valid_y = y[valid_idx]

#### Assignment 5:  refer the math defination of loss function in our slides and try to understand how to code them in sklearn

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,log_loss

#### MAE
The mean absolute error (MAE) is the simplest regression error metric to understand. We’ll calculate the residual for every data point, taking only the absolute value of each so that negative and positive residuals do not cancel out. We then take the average of all these residuals. Effectively, MAE describes the typical magnitude of the residuals. (MAE tells us how big of an error we can expect from the forecast on average.)

##### Note: I compared my function mas_func with the oputput from mean_absolute_error(x,x_hat), and they match. meaning my function is working. 

In [28]:
x = [6,5,6,8]
x_hat = [3,5,9,3]
mean_absolute_error(x,x_hat)

2.75

In [29]:
def mas_func(a,b):
 mae_sum = 0
 for x,y in zip(a,b):
    mae_sum += abs(x - y)
    print(mae_sum)
 mae = mae_sum/len(a)
 return mae
    
x = [6,5,6,8]
x_hat = [3,5,9,3]
mas_func(x, x_hat)

3
3
6
11


2.75

### MSE 
the difference between the actual and the predicted values, But squares the difference before summing them all instead of using the absolute value. 

##### note: I compared my function mse_func with the output from mean_squared_error(x,x_hat) and they match, meaning my function is working.

In [30]:
x = [6,5,6,8]
x_hat = [3,5,9,3]
mean_squared_error(x,x_hat)

10.75

In [31]:
def mse_func(a,b):
 mse_sum = 0
 for x , y in zip(a,b):
    mse_sum += abs(x - y)**2
    #print(mse_sum)
 mse = mse_sum/len(a)
 return mse
    
x = [6,5,6,8]
x_hat = [3,5,9,3]
mse_func(x, x_hat)

10.75